### ISSUE TITLE
Any plan to release an APPX package?

### ISSUE THREAD

**Issue by kumarharsh** [alistair23/bytewarden-windows#1]
I'd want to give it a sideload on my phone - is there any plan to release an APPX package with every release, or should I need to pull and build?

**Comment by alistair23** [comment]
On each tag I push the package to the Windows Store, so if you want to update with every release you can just install the app through the store.

I don't have plans to include the built binary in git as that just seems like a pain to deal with and would greatly bloat the size of the repo.

**Comment by alistair23** [comment]
If you are interested in pulling, building and testing that would be great. At the moment I'm waiting on an update to Xamarin Forms 2.5 though, so the list view is broken. The wrong item is selected when you click something (https://github.com/xamarin/Xamarin.Forms/issues/1439).

**Comment by kumarharsh** [comment]
Oh, it's in the store? Amazing!
As I couldn't find the official app yet, so I thought your fork won't be there too.

**Comment by alistair23** [comment]
Yeah, it is in the store. You can get it here: https://www.microsoft.com/en-us/store/p/bytewarden/9n248v7dk05k

It's in beta at the moment, there are some known issues. Especially relating to vertical layout issues. I have fixes but I'm stuck waiting on Xamarin Forms at the moment.

**Comment by kumarharsh** [comment]
Yeah, got it. Trying it out now.

**Comment by alistair23** [comment]
Great! Feel free to create issues here if you find any and I would appreciate a review in the store as well.

**Comment by kumarharsh** [comment]
OK, tried it out - the app doesn't have ability to autofill password, or show a notification like in Android?

**Comment by alistair23** [comment]
That is an Android Operating System feature that the app can utilise. There is no such feature on Windows Mobile that we can use to get the same functionality.

**Comment by kumarharsh** [comment]
Aah. I see. feared that. But doesn't that make the app *nearly* pointless - vault.bitwarden.com is there for access at all times, and maybe quite a bit faster too if I'm already using the browser.

Please don't take this comment personally - I've seen the amount of work you've done to make a UWP app a reality (I tried to do it too, but I had bitten off much more than I could chew). It's just disappointing to finally see that one usecase I wanted to not be possible :-(

But integration with Windows Hello is a nice feature to have - perhaps I'll find some use for the app 😉

**Comment by alistair23** [comment]
It depends. If you are happy to access bitwarden from the browser all the time then the app maybe isn't super useful. But the app
- Includes offline support if you don't have Internet access
- Integrates with Windows Hello
- Allows easy one button copy/paste functionality (not sure if the web vault allows that)
- Avoids the need to stay logged in via the browser all the time
- Is the best we are going to get on Windows 10 Mobile

**Comment by alistair23** [comment]
I find opening the app and using my Phone's IRIS scanner SO much faster then logging in via the browser.
