### ISSUE TITLE
Unable to change API URLs

### ISSUE THREAD

**Issue by darshanrampatel** [alistair23/bytewarden-windows#2]
Hi,

I can't see the button that allows changing the API URLs in the store version.

I have looked through the [code](https://github.com/alistair23/bytewarden-windows/blob/master/src/App/Pages/HomePage.cs#L34) and it looks as though the button should be being created but it's not.

Any ideas?

**Comment by darshanrampatel** [comment]
It looks like the button is just hidden (tabbing works...):

![image](https://user-images.githubusercontent.com/14162899/43849628-ca45f2ae-9b2d-11e8-8608-b666f327be71.png)

However, changing the API doesn't seem to work (note: my username is blanked out in the screenshot below):

![image](https://user-images.githubusercontent.com/14162899/43849776-2086c83c-9b2e-11e8-8076-3e35e3841525.png)

**Comment by alistair23** [comment]
Thanks for reporting an issue!

I won't get a chance to look into this until at least next week. Looking at what you have said it looks like the image for the button it's being applied. Are you able to try changing the transparency and see if that helps? Then we can narrow down for there.

As for the server error, that is a step harder and I don't really have a good way to test a custom server. I'll have to dig into that more.

**Comment by darshanrampatel** [comment]
The button issue was to do with the size of the image - see #3 

The issue with the custom API is because I'm using a local IP address for my BitWarden server - this means that the [**privateNetworkClientServer** capability](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations) needs to be enabled to allow for network connections over the local network. Since we already have the **internetClient** capability, I can't think of any reason why we shouldn't just also add the **privateNetworkClientServer** capability to the manifest?

Interestingly, on my Lumia 950, I _can_ connect to the internal IP, but not on my Windows desktop - I presume the versions in the store are the same for both?

**Comment by alistair23** [comment]
Ok, I have updated the app manifest to include that capability. It seems fine to me.

They are both the same version, I assume it has something to do with different access permissions for different Windows versions. As Windows Mobile is behind Windows.

**Comment by alistair23** [comment]
I merged your patches and fixed the capability issue. It's all pushed to master (along with other changes from Bitwareden). I'm going to test it over the weekend before submitting it to the store. If you can make sure it fixes your issue then that would be great!

**Comment by darshanrampatel** [comment]
Have tested this (on both desktop and mobile) and I can now connect to my local BitWarden server! Thanks for this.

**Comment by alistair23** [comment]
Awesome! Thanks for pointing out the fix
