### ISSUE TITLE
Advice on further enhancements/changes

### ISSUE THREAD

**Issue by darshanrampatel** [alistair23/bytewarden-windows#4]
While using the app on mobile, I can see a few areas where the layout could be improved slightly (e.g. the settings page is very small on mobile).

Do you want new issues for every potential change to review them first or would you rather just get PRs that you can review?

**Comment by alistair23** [comment]
Pull requests would be awesome. I am more then happy to review and merge PRs. I don't see a need to have an issue for each one. I am aware there are a lot of layout issues.

The one caveat is that I would like to keep the standard App code as close as possible to the Bitwarden code to make it as easy as possible to stay up-to-date with the Bitwarden security fixes and features. So where possible it'd be best to have the code accepted to Bitwarden and if not I'd like to keep the fixes as self contained and simple as possible.

I understand that isn't always possible though, so fixes are still very appreciated!

**Comment by darshanrampatel** [comment]
Thanks for the confirmation!
